CREATE TABLE IF NOT EXISTS authors
(
    author_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      varchar(256) UNIQUE NOT NULL,
    date_born date                NOT NULL
);

CREATE TABLE IF NOT EXISTS books
(
    book_id     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       varchar(256) UNIQUE NOT NULL,
    description varchar(1024)       NOT NULL,
    release     date                NOT NULL
);

CREATE TABLE IF NOT EXISTS comments
(
    comment_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content    varchar(1024) NOT NULL,
    book_id    bigint REFERENCES books ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS authors_books
(
    author_id bigint REFERENCES authors ON DELETE CASCADE,
    book_id   bigint REFERENCES books ON DELETE CASCADE,
    CONSTRAINT pk_authors_books PRIMARY KEY (author_id, book_id)
);